use_small_heuristics = "Max"
fn_args_density = "Compressed"
enum_discrim_align_threshold = 50
struct_field_align_threshold = 50
where_single_line = true
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
wrap_comments = true
overflow_delimited_expr = true