[package]
name = "pinyin_ime"
version = "0.1.0"
authors = ["xalanq <xalanq@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pbr = "1.0.1"
jieba-rs = "0.2"
pinyin = "0.4"
